### ISSUE TITLE
RDS: open links in a new window/tab

### ISSUE THREAD

**Issue by doaa-altarawy** [MolSSI/QCArchiveWebapps#60]
**Webapp**
RDS

It would be better to open links in a new window to avoid losing your current plots accidentally when clicking on the feature request for instance.

As far as I know, this is not supported in Markdown, so we may need to try maybe Kramdown or alike.

**Comment by dgasmith** [comment]
We may have to go to HTML tags: https://github.com/plotly/dash-html-components/issues/23

**Comment by yogesh-ezest** [comment]
> We may have to go to HTML tags: [plotly/dash-html-components#23](https://github.com/plotly/dash-html-components/issues/23)

How to do the same in dashtable?

**Comment by yogesh-ezest** [comment]
@dgasmith could you please provide the suggestions to open link in new tab using markdown. Or Do you have any idea how do I create link in dashtable cell.

I tried using markdown but link is opened in the same tab, I need the url should be opened in new tab.

Thanks

**Comment by dgasmith** [comment]
Kramdown support `[link name](url_link){:target="_blank"}`. GH-style Markdown supports it via raw HTML `<a href="example.com" target="_blank">New Tab</a>`, but Plotly-style Markdown is a limited subset, which is on purpose for security issues I believe.

**Comment by mattwelborn** [comment]
Resolved by #69?

**Comment by dgasmith** [comment]
Yup.
